spring.application.name=teamSync-app

#Temp security
spring.security.user.name=dev
spring.security.user.password=devpass

#Postgres Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/teamSync-db
spring.datasource.username=teamSyncUser
spring.datasource.password=teamSyncPass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true