services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=teamSync-db'
      - 'POSTGRES_PASSWORD=teamSyncPass'
      - 'POSTGRES_USER=teamSyncUser'
    ports:
      - '5420'
